-- Images
Image.new("Alien","/Assets/Alien.png")
Image.new("button","/Assets/temp_button.png")
Image.new("button_squ","/Assets/temp_button_squ.png")
Image.new("Arrow_left","/Assets/arrow_left.png")
Image.new("Arrow_right","/Assets/arrow_right.png")
Image.new("Arrow_red","/Assets/arrow_red.png")
Image.new("Check","/Assets/check.png")
Image.new("Outside_1","/Assets/outside_1.png")
Image.new("Outside_2","/Assets/outside_2.png")

Image.new("Alien_1","/Assets/Customer_Aliens/Dripped_Alien_1.png")
Image.new("Alien_2","/Assets/Customer_Aliens/Dripped_Alien_2.png")
Image.new("Alien_3","/Assets/Customer_Aliens/OldLady_Alien_1.png")
Image.new("Alien_4","/Assets/Customer_Aliens/OldLady_Alien_2.png")
Image.new("Alien_5","/Assets/Customer_Aliens/Phone_Alien_1.png")
Image.new("Alien_6","/Assets/Customer_Aliens/Phone_Alien_2.png")
Image.new("Alien_7","/Assets/Customer_Aliens/Shy_Alien_1.png")
Image.new("Alien_8","/Assets/Customer_Aliens/Shy_Alien_2.png")
Image.new("Alien_9","/Assets/Customer_Aliens/Smirk_Alien_1.png")
Image.new("Alien_10","/Assets/Customer_Aliens/Smirk_Alien_2.png")
Image.new("Alien_11","/Assets/Customer_Aliens/Surprised_Alien_1.png")
Image.new("Alien_12","/Assets/Customer_Aliens/Surprised_Alien_2.png")

Image.new("FrontDesk","/Assets/FrontDesk/FrontDesk_Bg.png")
Image.new("FrontDesk_Computer","/Assets/FrontDesk/FrontDesk_Computer_Light.png")

Image.new("CheckUp","/Assets/CheckUp/CheckUp_Bg_Sketch.png")
Image.new("CheckUp_Bath","/Assets/CheckUp/CheckUp_Bath_Sketch.png")
Image.new("CheckUp_Bed","/Assets/CheckUp/CheckUp_Bed_Sketch.png")
Image.new("CheckUp_Bubbles","/Assets/CheckUp/Taking_Bath.png")

Image.new("CareUnit","/Assets/CareUnit/CareUnit_Bg_Sketch.png")
Image.new("CareUnit_Bandage_1","/Assets/CareUnit/CareUnit_Bandage_1_Sketch.png")
Image.new("CareUnit_Bandage_2","/Assets/CareUnit/CareUnit_Bandage_2_Sketch.png")
Image.new("CareUnit_RubberHammer_1","/Assets/CareUnit/CareUnit_RubberHammer_1_Sketch.png")
Image.new("CareUnit_RubberHammer_2","/Assets/CareUnit/CareUnit_RubberHammer_2_Sketch.png")
Image.new("CareUnit_Pills_1","/Assets/CareUnit/CareUnit_Pills_1_Sketch.png")
Image.new("CareUnit_Pills_2","/Assets/CareUnit/CareUnit_Pills_2_Sketch.png")
Image.new("CareUnit_Xray_1","/Assets/CareUnit/CareUnit_Xray_1_Sketch.png")
Image.new("CareUnit_Xray_2","/Assets/CareUnit/CareUnit_Xray_2_Sketch.png")

Image.new("Catlike_None_1","/Assets/Catlike_sprites/Catlike_None_1.png")
Image.new("Catlike_Antenne_1","/Assets/Catlike_sprites/Catlike_Antenne_1.png")
Image.new("Catlike_Antenne_2","/Assets/Catlike_sprites/Catlike_Antenne_2.png")
Image.new("Catlike_Cold_1","/Assets/Catlike_sprites/Catlike_Cold_1.png")
Image.new("Catlike_Cold_2","/Assets/Catlike_sprites/Catlike_Cold_2.png")
Image.new("Catlike_Scratch_1","/Assets/Catlike_sprites/Catlike_Scratch_1.png")
Image.new("Catlike_Scratch_2","/Assets/Catlike_sprites/Catlike_Scratch_2.png")
Image.new("Catlike_Stinky_1","/Assets/Catlike_sprites/Catlike_Stinky_1.png")
Image.new("Catlike_Stinky_2","/Assets/Catlike_sprites/Catlike_Stinky_2.png")
Image.new("Catlike_Tummy_1","/Assets/Catlike_sprites/Catlike_Tummy_1.png")
Image.new("Catlike_Tummy_2","/Assets/Catlike_sprites/Catlike_Tummy_2.png")

Image.new("Doglike_None_1","/Assets/Doglike_sprites/Doglike_None_1.png")
Image.new("Doglike_Antenne_1","/Assets/Doglike_sprites/Doglike_Antenne_1.png")
Image.new("Doglike_Antenne_2","/Assets/Doglike_sprites/Doglike_Antenne_2.png")
Image.new("Doglike_Cold_1","/Assets/Doglike_sprites/Doglike_Cold_1.png")
Image.new("Doglike_Cold_2","/Assets/Doglike_sprites/Doglike_Cold_2.png")
Image.new("Doglike_Scratch_1","/Assets/Doglike_sprites/Doglike_Scratch_1.png")
Image.new("Doglike_Scratch_2","/Assets/Doglike_sprites/Doglike_Scratch_2.png")
Image.new("Doglike_Stinky_1","/Assets/Doglike_sprites/Doglike_Stinky_1.png")
Image.new("Doglike_Stinky_2","/Assets/Doglike_sprites/Doglike_Stinky_2.png")
Image.new("Doglike_Tummy_1","/Assets/Doglike_sprites/Doglike_Tummy_1.png")
Image.new("Doglike_Tummy_2","/Assets/Doglike_sprites/Doglike_Tummy_2.png")

Image.new("Birdlike_None_1","/Assets/Birdlike_sprites/Birdlike_None_1.png")
Image.new("Birdlike_Antenne_1","/Assets/Birdlike_sprites/Birdlike_Antenne_1.png")
Image.new("Birdlike_Antenne_2","/Assets/Birdlike_sprites/Birdlike_Antenne_2.png")
Image.new("Birdlike_Cold_1","/Assets/Birdlike_sprites/Birdlike_Cold_1.png")
Image.new("Birdlike_Cold_2","/Assets/Birdlike_sprites/Birdlike_Cold_2.png")
Image.new("Birdlike_Scratch_1","/Assets/Birdlike_sprites/Birdlike_Scratch_1.png")
Image.new("Birdlike_Scratch_2","/Assets/Birdlike_sprites/Birdlike_Scratch_2.png")
Image.new("Birdlike_Stinky_1","/Assets/Birdlike_sprites/Birdlike_Stinky_1.png")
Image.new("Birdlike_Stinky_2","/Assets/Birdlike_sprites/Birdlike_Stinky_2.png")
Image.new("Birdlike_Tummy_1","/Assets/Birdlike_sprites/Birdlike_Tummy_1.png")
Image.new("Birdlike_Tummy_2","/Assets/Birdlike_sprites/Birdlike_Tummy_2.png")

Image.new("Wormlike_None_1","/Assets/Wormlike_sprites/Wormlike_None_1.png")
Image.new("Wormlike_Antenne_1","/Assets/Wormlike_sprites/Wormlike_Antenne_1.png")
Image.new("Wormlike_Antenne_2","/Assets/Wormlike_sprites/Wormlike_Antenne_2.png")
Image.new("Wormlike_Cold_1","/Assets/Wormlike_sprites/Wormlike_Cold_1.png")
Image.new("Wormlike_Cold_2","/Assets/Wormlike_sprites/Wormlike_Cold_2.png")
Image.new("Wormlike_Scratch_1","/Assets/Wormlike_sprites/Wormlike_Scratch_1.png")
Image.new("Wormlike_Scratch_2","/Assets/Wormlike_sprites/Wormlike_Scratch_2.png")
Image.new("Wormlike_Stinky_1","/Assets/Wormlike_sprites/Wormlike_Stinky_1.png")
Image.new("Wormlike_Stinky_2","/Assets/Wormlike_sprites/Wormlike_Stinky_2.png")
Image.new("Wormlike_Tummy_1","/Assets/Wormlike_sprites/Wormlike_Tummy_1.png")
Image.new("Wormlike_Tummy_2","/Assets/Wormlike_sprites/Wormlike_Tummy_2.png")

Image.new("Horselike_None_1","/Assets/Horselike_sprites/Horselike_None_1.png")
Image.new("Horselike_Antenne_1","/Assets/Horselike_sprites/Horselike_Antenne_1.png")
Image.new("Horselike_Antenne_2","/Assets/Horselike_sprites/Horselike_Antenne_2.png")
Image.new("Horselike_Cold_1","/Assets/Horselike_sprites/Horselike_Cold_1.png")
Image.new("Horselike_Cold_2","/Assets/Horselike_sprites/Horselike_Cold_2.png")
Image.new("Horselike_Scratch_1","/Assets/Horselike_sprites/Horselike_Scratch_1.png")
Image.new("Horselike_Scratch_2","/Assets/Horselike_sprites/Horselike_Scratch_2.png")
Image.new("Horselike_Stinky_1","/Assets/Horselike_sprites/Horselike_Stinky_1.png")
Image.new("Horselike_Stinky_2","/Assets/Horselike_sprites/Horselike_Stinky_2.png")
Image.new("Horselike_Tummy_1","/Assets/Horselike_sprites/Horselike_Tummy_1.png")
Image.new("Horselike_Tummy_2","/Assets/Horselike_sprites/Horselike_Tummy_2.png")

Image.new("Bunnylike_None_1","/Assets/Bunnylike_sprites/Bunnylike_None_1.png")
Image.new("Bunnylike_Antenne_1","/Assets/Bunnylike_sprites/Bunnylike_Antenne_1.png")
Image.new("Bunnylike_Antenne_2","/Assets/Bunnylike_sprites/Bunnylike_Antenne_2.png")
Image.new("Bunnylike_Cold_1","/Assets/Bunnylike_sprites/Bunnylike_Cold_1.png")
Image.new("Bunnylike_Cold_2","/Assets/Bunnylike_sprites/Bunnylike_Cold_2.png")
Image.new("Bunnylike_Scratch_1","/Assets/Bunnylike_sprites/Bunnylike_Scratch_1.png")
Image.new("Bunnylike_Scratch_2","/Assets/Bunnylike_sprites/Bunnylike_Scratch_2.png")
Image.new("Bunnylike_Stinky_1","/Assets/Bunnylike_sprites/Bunnylike_Stinky_1.png")
Image.new("Bunnylike_Stinky_2","/Assets/Bunnylike_sprites/Bunnylike_Stinky_2.png")
Image.new("Bunnylike_Tummy_1","/Assets/Bunnylike_sprites/Bunnylike_Tummy_1.png")
Image.new("Bunnylike_Tummy_2","/Assets/Bunnylike_sprites/Bunnylike_Tummy_2.png")

Image.new("Fishlike_None_1","/Assets/Fishlike_sprites/Fishlike_None_1.png")
Image.new("Fishlike_Antenne_1","/Assets/Fishlike_sprites/Fishlike_Antenne_1.png")
Image.new("Fishlike_Antenne_2","/Assets/Fishlike_sprites/Fishlike_Antenne_2.png")
Image.new("Fishlike_Cold_1","/Assets/Fishlike_sprites/Fishlike_Cold_1.png")
Image.new("Fishlike_Cold_2","/Assets/Fishlike_sprites/Fishlike_Cold_2.png")
Image.new("Fishlike_Scratch_1","/Assets/Fishlike_sprites/Fishlike_Scratch_1.png")
Image.new("Fishlike_Scratch_2","/Assets/Fishlike_sprites/Fishlike_Scratch_2.png")
Image.new("Fishlike_Stinky_1","/Assets/Fishlike_sprites/Fishlike_Stinky_1.png")
Image.new("Fishlike_Stinky_2","/Assets/Fishlike_sprites/Fishlike_Stinky_2.png")
Image.new("Fishlike_Tummy_1","/Assets/Fishlike_sprites/Fishlike_Tummy_1.png")
Image.new("Fishlike_Tummy_2","/Assets/Fishlike_sprites/Fishlike_Tummy_2.png")

Image.new("Ratlike_None_1","/Assets/Ratlike_sprites/Ratlike_None_1.png")
Image.new("Ratlike_Antenne_1","/Assets/Ratlike_sprites/Ratlike_Antenne_1.png")
Image.new("Ratlike_Antenne_2","/Assets/Ratlike_sprites/Ratlike_Antenne_2.png")
Image.new("Ratlike_Cold_1","/Assets/Ratlike_sprites/Ratlike_Cold_1.png")
Image.new("Ratlike_Cold_2","/Assets/Ratlike_sprites/Ratlike_Cold_2.png")
Image.new("Ratlike_Scratch_1","/Assets/Ratlike_sprites/Ratlike_Scratch_1.png")
Image.new("Ratlike_Scratch_2","/Assets/Ratlike_sprites/Ratlike_Scratch_2.png")
Image.new("Ratlike_Stinky_1","/Assets/Ratlike_sprites/Ratlike_Stinky_1.png")
Image.new("Ratlike_Stinky_2","/Assets/Ratlike_sprites/Ratlike_Stinky_2.png")
Image.new("Ratlike_Tummy_1","/Assets/Ratlike_sprites/Ratlike_Tummy_1.png")
Image.new("Ratlike_Tummy_2","/Assets/Ratlike_sprites/Ratlike_Tummy_2.png")

-- Fonts
Font.new("Spacy","/Assets/Spacy.ttf",16)
Font.new("Spacy_2","/Assets/Spacy.ttf",24)
Font.new("Spacy_3","/Assets/Spacy.ttf",32)
Font.new("Spacy_4","/Assets/Spacy.ttf",48)
Font.new("Spacy_5","/Assets/Spacy.ttf",96)

-- SFX
Sound.new("ding","/Assets/ding.mp3","static")
Sound.new("thx_1","/Assets/thx.mp3","static")
Sound.new("thx_2","/Assets/thx_2.mp3","static")
Sound.new("thx_3","/Assets/thx_3.mp3","static")
Sound.new("thx_4","/Assets/thx_4.mp3","static")
Sound.new("no_1","/Assets/no_1.mp3","static")
Sound.new("no_2","/Assets/no_2.mp3","static")
Sound.new("no_3","/Assets/no_3.mp3","static")
Sound.new("no_4","/Assets/no_4.mp3","static")
Sound.new("Spend","/Assets/clear.mp3","static")
Sound.new("No_money","/Assets/deny.mp3","static")
Sound.new("Door","/Assets/door.mp3","static")
Sound.new("Swipe","/Assets/swipe.mp3","static")

-- Songs
Sound.new("beep","/Assets/beepboop.mp3")
Sound.new("gloorp","/Assets/gloorp.mp3")
Sound.new("pit","/Assets/pit_stop.mp3")
Sound.new("ggg","/Assets/glurp-glurp-glurp.mp3")
Sound.new("saturn","/Assets/saturns_regards.mp3")
Sound.new("planetx","/Assets/planetx.mp3")
